### ISSUE TITLE
Missing comma break admin search

### ISSUE THREAD

**Issue by code-review-doctor** [unlimitedlabs/orchestra#818]
There is a missing comma at the end of line 64:

https://github.com/b12io/orchestra/blob/1ba58d26c508e89d2050dc9b0c8439eb1eadd014/orchestra/admin.py#L63-L65

that results in `'assignment__task__project__short_description'` and `'assignment__worker__user__username'` being concatenated together when search is done. This will break search when Django tries to lookup field called `'assignment__task__project__short_descriptionassignment__worker__user__username'`, which of course does not exist.

The fix is to change to

```py
'assignment__task__step__name', 
'assignment__task__project__short_description',
'assignment__worker__user__username') 
```
I can do a PR to fix if you want :)

**Comment by marcua** [comment]
Thank you so much @code-review-doctor! We'd really appreciate a PR!

**Comment by marcua** [comment]
Thanks again @code-review-doctor!
